name: Run Tests

on:
    push:

jobs:
    run-tests:
        runs-on: ubuntu-latest
        
        env: 
              CI_COMMIT_MESSAGE: Build Module-Packages
              CI_COMMIT_AUTHOR: fruithost | Modules Builder
              
        strategy:
            matrix:
                php: [8.1]

        name: PHP ${{ matrix.php }}

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Get Sources
              run: |
                git clone https://github.com/fruithost/Panel.git src
                    
            - name: Generate API docs
              uses: phpDocumentor/phpDocumentor@master
              with:
                args: -d src -t build/docs

            - name: Commit changes
              if: github.event_name == 'push'
              run: |
                set -e
                cd $GITHUB_WORKSPACE/${{github.repository}}.wiki
                cp -r $GITHUB_WORKSPACE/${{github.repository}}/wiki/* .
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "fruithost@users.noreply.github.com"
                git add .
                git diff-index --quiet HEAD || git commit -m "${{ env.CI_COMMIT_MESSAGE }}" && git push
