name: Run Tests

on:
    push:

jobs:
    run-tests:
        runs-on: ubuntu-latest
        
        env: 
              CI_COMMIT_MESSAGE: Build Module-Packages
              CI_COMMIT_AUTHOR: fruithost | Modules Builder
              
        strategy:
            matrix:
                php: [8.1]

        name: PHP ${{ matrix.php }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: ${{ matrix.coverage }}
                  tools: composer:v2
                  ini-values: date.timezone='UTC'
            
            - name: Get Sources
              run: |
                git clone https://github.com/fruithost/Panel.git ./src/
                git clone https://github.com/fruithost/Documentation.wiki.git ./wiki/
                git clone https://github.com/clean/phpdoc-md.git ./phpdoc/

            - name: Create temporary Config file
              run: |
                    touch ./config.php
                    echo "<?php" >> ./config.php
                    echo "return (object)[" >> ./config.php
                    echo "'rootNamespace' => 'Clean\PhpDocMd\Example'," >> ./config.php
                    echo "'destDirectory' => 'docs'," >> ./config.php
                    echo "'format' => 'github'," >> ./config.php
                    echo "'destDirectory' => 'docs'," >> ./config.php
                    echo "'classes' => [" >> ./config.php
                    echo "'src\**'" >> ./config.php
                    echo "]];" >> ./config.php
                    
            - name: Generating documentation...
              run: |
                  ./phpdoc/bin/phpdoc-md -h
                  ./phpdoc/bin/phpdoc-md ./config.php
             
            - name: Commit changes
              if: github.event_name == 'push'
              run: |
                set -e
                cp ./build/ ./wiki/
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "fruithost@users.noreply.github.com"
                git add .
                git diff-index --quiet HEAD || git commit -m "${{ env.CI_COMMIT_MESSAGE }}" && git push
