name: Run Tests

on:
    push:

jobs:
    run-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [8.1]

        name: PHP ${{ matrix.php }}

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Generate API docs
              uses: phpDocumentor/phpDocumentor@master
              with:
                args: -d src -t build/docs
