name: Run Tests

on:
    push:

jobs:
    run-tests:
        runs-on: ubuntu-latest
        
        env: 
              CI_COMMIT_MESSAGE: Build Module-Packages
              CI_COMMIT_AUTHOR: fruithost | Modules Builder
              
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
           
            - name: Get Sources
              run: |
                git clone https://github.com/fruithost/Panel.git ./src/
                git clone https://github.com/fruithost/Documentation.wiki.git ./wiki/                                 
                       
            - name: Update wiki with PHP project documentation
              uses: impresscms-dev/phpdocs-wiki-update-action@v2.2.20
              with:
                  engine: clean/phpdoc-md
                  class_root_namespace: fruithost
                  setup_php: true
                  include: |
                    src\**
                    
            - name: Commit changes
              if: github.event_name == 'push'
              run: |
                set -e
                cp ./build/ ./wiki/
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "fruithost@users.noreply.github.com"
                git add .
                git diff-index --quiet HEAD || git commit -m "${{ env.CI_COMMIT_MESSAGE }}" && git push
